// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUXqUHFU2Lf1b0bwWULsD0PhOTQDwytSA',
    appId: '1:1074199428257:web:01112a219d1240ee3b84e0',
    messagingSenderId: '1074199428257',
    projectId: 'charusat-maps-1c7ee',
    authDomain: 'charusat-maps-1c7ee.firebaseapp.com',
    storageBucket: 'charusat-maps-1c7ee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUXqUHFU2Lf1b0bwWULsD0PhOTQDwytSA',
    appId: '1:1074199428257:android:01112a219d1240ee3b84e0',
    messagingSenderId: '1074199428257',
    projectId: 'charusat-maps-1c7ee',
    storageBucket: 'charusat-maps-1c7ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUXqUHFU2Lf1b0bwWULsD0PhOTQDwytSA',
    appId: '1:1074199428257:ios:01112a219d1240ee3b84e0',
    messagingSenderId: '1074199428257',
    projectId: 'charusat-maps-1c7ee',
    storageBucket: 'charusat-maps-1c7ee.firebasestorage.app',
    iosClientId: '1074199428257-0000000000000000.apps.googleusercontent.com',
    iosBundleId: 'com.example.charusat_maps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUXqUHFU2Lf1b0bwWULsD0PhOTQDwytSA',
    appId: '1:1074199428257:ios:01112a219d1240ee3b84e0',
    messagingSenderId: '1074199428257',
    projectId: 'charusat-maps-1c7ee',
    storageBucket: 'charusat-maps-1c7ee.firebasestorage.app',
    iosClientId: '1074199428257-0000000000000000.apps.googleusercontent.com',
    iosBundleId: 'com.example.charusat_maps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUXqUHFU2Lf1b0bwWULsD0PhOTQDwytSA',
    appId: '1:1074199428257:web:01112a219d1240ee3b84e0',
    messagingSenderId: '1074199428257',
    projectId: 'charusat-maps-1c7ee',
    authDomain: 'charusat-maps-1c7ee.firebaseapp.com',
    storageBucket: 'charusat-maps-1c7ee.firebasestorage.app',
  );
}
